### PR TITLE
Support Django 1.11 & 2.0

### PR DESCRIPTION
**Pull request by michael-k**
Tests are still failing, because Django master is not supported.
https://travis-ci.org/michael-k/django-querysetsequence/builds/267246035

### CODE REVIEW

**Comment by clokep** [comment]
This seems to completely drop support for Django 1.9 from testing, is that done on purpose?

**Comment by michael-k** [comment]
Yes, see commit bdd62bc.  Django 1.9 reached its end of life over 4 months ago.
https://www.djangoproject.com/weblog/2017/apr/04/security-releases/

**Comment by clokep** [comment]
OK, but does it not *work* or are you just removing it because it's EOL?

**Comment by michael-k** [comment]
It should work, I haven't looked into it.

Btw. I'm working on another commit to add Django 2.0 support.

**Comment by michael-k** [comment]
I've added two more commits.  Tests are still running, but they are looking good so far: https://travis-ci.org/michael-k/django-querysetsequence/builds/267263088

I'll check later or tomorrow if there's more work to do.

**Comment by michael-k** [comment]
@clokep Can you merge this?  The PR is not against master, but your branch `update-tox`.

**Comment by clokep** [comment]
I'll take a look at this in the next couple of days! I missed the notification saying you had pushed, sorry!

**Comment by clokep** [comment]
Looks great. Thanks! 👍 Going to merge this to my other PR and clean-up the README/changelog a bit.

**Pull request merged**
