### PR TITLE
Prevent queryset evaluation + don't mix return types

### PR DESCRIPTION
**Pull request by jpic**
Hi !

Thanks a heap for sharing this nifty module !

This patch doesn't seem to break any test, what do you think ?

### CODE REVIEW

**Comment by clokep** [comment]
Seems pretty reasonable. I'm going to think about whether there's a better way for us to be testing for database hits (i.e. `QuerySet` evaluation) briefly before merging this. I had forgotten that casting to `bool` evaluates a `QuerySet`!

**Comment by clokep** [comment]
Cool, looks like we can use [`assertNumQueries`](https://docs.djangoproject.com/en/1.9/topics/testing/tools/#django.test.TransactionTestCase.assertNumQueries) to test that. I just verified that that this change causes a `filter()` call to not evaluate any `QuerySets`. Thanks!

**Comment by clokep** [comment]
I pushed tests for this in baaf4484649cbec5c1f80c684b1fa4177b6e23fd.

**Comment by jpic** [comment]
Thanks, you rock !

**Pull request merged**
