### PR TITLE
Keep unpatched args for introspection

### PR DESCRIPTION
**Pull request by jpic**
#21 :golf:

### CODE REVIEW

**Comment by clokep** [comment]
@jpic I'm not 100% sure I follow how this is fixing the issue. How/where would this be used? Can you add a test for what this is for?

**Comment by jpic** [comment]
The purpose is to check if a given model instance is part of the querysetsequence, perhaps you would prefer to expose a public API for this ?

    if not qss.has_model(model_instance):
       raise ValidationError('Choice is not available')

**Comment by clokep** [comment]
@jpic Can you give a more concrete example? What is `model_instance`? I also don't understand when you would do this.

**Comment by jpic** [comment]
I would like to validate if a given model instance is in a queryset sequence.

For example:

    model = SomeModel.objects.get(pk=some_pk)
    if model not in queryset_sequence:
        raise Exception('You need a model with a pk that is in the queryset sequence')

Does this make more sense ?

**Comment by clokep** [comment]
@jpic Yes, that makes more sense. I'm not sure how this PR fixes that issue though, where would this `_args` get used?

It'd also be good to add a test-case for this.

**Comment by clokep** [comment]
This class no longer exists, I'm unsure if this is still necessary, but please open a new PR with updated changes if it is required for your use-case!

**Pull request closed without merging**
