### PR TITLE
Add support for Django 1.11 (and master)

### PR DESCRIPTION
**Pull request by clokep**
This adds support for Django 1.11 and master by adapting to new APIs.

### CODE REVIEW

**Comment by clokep** [comment]
This still has a couple of failing tests I'm working through.

**Comment by blueyed** [comment]
Nice!
Have you made additional progress on it already? / What is the state of this?

**Comment by clokep** [comment]
@blueyed I haven't had a chance to look into this more, although I suspect you *might* be able to replace this with [`union()`](https://docs.djangoproject.com/en/1.11/ref/models/querysets/#union) method in Django 1.11, let me know if you try that out!

**Comment by clokep** [comment]
I should also mention that I've been unable to figure out the couple of tests that are failing -- the reason is not obvious and I've been unable to reduce the test-case farther to figure out what's wrong. If you have a chance to look, I'd love some more eyes on it!

**Comment by blueyed** [comment]
@clokep 
Thanks for the update!
I have not tried `union()` but just came across this with the last test failures we have for Django 1.11.

We're basically using it for/with https://github.com/yourlabs/django-autocomplete-light, but in custom ways also.

I could make our tests passing using this branch, but those are very basic.

**Comment by michael-k** [comment]
The main limitation of [`union()`](https://docs.djangoproject.com/en/1.11/ref/models/querysets/#union) is:

> Passing different models works as long as the SELECT list is the same in all QuerySets (at least the types, the names don’t matter as long as the types in the same order).

**Comment by clokep** [comment]
@michael-k Right, but it's a lot less hacky then this. If you *can* use it, I'd highly suggest using that instead.

**Comment by clokep** [comment]
I think this is ready to go, if tests pass!

**Comment by clokep** [comment]
Just pushed version 0.8 to pypi.

**Pull request merged**
