### PR TITLE
Add ability to explicitly set model

### PR DESCRIPTION
**Pull request by CountZachula**
More extensible this way, in my opinion, especially when implementing custom filter/sort functionality. Any input?

### CODE REVIEW

**Comment by clokep** [comment]
This seems pretty sane at first glance. Thanks for adding tests, by the way! I have a busy day today, but I'll take a deeper tonight or tomorrow!

**Comment by CountZachula** [comment]
Thanks!

I want to commend you for this handy module. I'd been struggling to find a way to union QuerySets across several databases then filter/sort without much overhead on my part (e.g. building a wrapper around QuerySet). My scenario involves pulling data from various databases across the U.S. and Canada and Ii's working beautifully! 

This PR was inspired by the fact that Django REST Framework asserts equality between the filter model and QuerySet model types. Having the ability to explicitly set the model allows me to use the DRF's DjangoFilterBackend. There is definitely room for smarter introspection. I'm open to any comments/complaints.

Here's what my ViewSet looks like:
```
class TagSerialViewViewSet(viewsets.ReadOnlyModelViewSet):
    """
    Represents TagSerialViewViewSet.
    """

    queryset = QuerySetSequence(
        TagSerialView.objects.all(),
        TagSerialView.objects.using('ca').all(),
        model=TagSerialView
    )
    serializer_class = TagSerialViewSerializer
    filter_backends = (filters.DjangoFilterBackend,)
    filter_class = TagSerialViewFilterSet
    pagination_class = FullResultsPagination
```

**Comment by clokep** [comment]
> I want to commend you for this handy module. I'd been struggling to find a way to union QuerySets across several databases then filter/sort without much overhead on my part (e.g. building a wrapper around QuerySet). My scenario involves pulling data from various databases across the U.S. and Canada and it's working beautifully! 

I'm glad you've found this useful!

> This PR was inspired by the fact that Django REST Framework asserts equality between the filter model and QuerySet model types. Having the ability to explicitly set the model allows me to use DRF's DjangoFilterBackend. There is definitely room for smarter introspection. I'm open to any comments/complaints.

Interesting, I've also used this code with Django REST Framework, but haven't run into this issue,  because I didn't use the `DjangoFilterBackend`

My initial thought was to make `QuerySetSequenceModel` a `Model` that introspecs the underlying `QuerySets` and has "fields" that match between all the `QuerySets`, but I haven't had time to consider that at all. This wouldn't work for your use case, anyway, so I suspect this is the reasonable solution.

In your situation, you might be able to do `queryset = SerialNumber.objects.all() | SerialNumber.objects.using('ca').all()`, if that doesn't work then it seems that overriding the model is the only way to do it.

**Comment by CountZachula** [comment]
> My initial thought was to make QuerySetSequenceModel a Model that introspecs the underlying QuerySets and has "fields" that match between all the QuerySets, but I haven't had time to consider that at all. This wouldn't work for your use case, anyway, so I suspect this is the reasonable solution.

This was exactly my thought.

> In your situation, you might be able to do queryset = SerialNumber.objects.all() | SerialNumber.objects.using('ca').all(), if that doesn't work then it seems that overriding the model is the only way to do it.

This was the first route I took. Unfortunately, `queryset.filter()` does not take multiple databases into account. I'd need to override `.filter()` and iterate over each database instance that might exist.

**Comment by clokep** [comment]
> This was the first route I took. Unfortunately, `queryset.filter()` does not take multiple databases into account. I'd need to override `.filter()` and iterate over each database instance that might exist.

Ah-ha! Makes sense. :) Thanks for the explanation! I need to look closer at the test cases, but I think this is ready to merge.

**Comment by clokep** [comment]
Thanks! :+1: I cleaned up a few things in 06d93378dda965023fb657189f1a855cee136229.

**Pull request merged**
